---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/storage: loki-stack
spec:
  capacity:
    storage: "10Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/monitor-stack/loki    #изменить по необходимости, путь на ноде мониторинга
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - nodename             #имя ноды мониторинга

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/storage: loki-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchExpressions:
      - key: app.kubernetes.io/storage
        operator: In
        values:
          - loki-stack
  storageClassName: local-storage
